namespace XamlIslandsCpp {
	enum AppTheme {
		Light,
		Dark
	};

	enum WindowBackdrop {
		SolidColor,
		Acrylic,
		Mica,
		MicaAlt
	};

	runtimeclass Settings {
		Settings();
		
		Boolean IsCustomTitleBarEnabled;
		event Windows.Foundation.EventHandler<Boolean> IsCustomTitleBarEnabledChanged;

		AppTheme Theme;
		event Windows.Foundation.EventHandler<AppTheme> ThemeChanged;

		WindowBackdrop Backdrop;
		event Windows.Foundation.EventHandler<WindowBackdrop> BackdropChanged;
	}
}
